name: api_car_repository
description: The Repo that handle api
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.2.1

  cupertino_icons: ^1.0.8
#  firebase_auth: ^5.2.1
#  cloud_firestore: ^5.4.1
  rxdart: ^0.28.0
  http: ^1.2.2

  #for env variables:
  flutter_dotenv: ^5.2.1

  logger: ^2.0.2

  shared_preferences: ^2.0.13 #for persitant cache data


  api_user_repository: #import api repo
    path: ../api_user_repository


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
